### ISSUE TITLE
Обернуть в дефайн метафункции рефлексии. 

### ISSUE THREAD

**Issue by aaashyrov** [Shidlowski/Alisher_lessons#42]
https://github.com/Shidlowski/Alisher_lessons/blob/master/Alisher_level_2/istorage/include/storagelib/pch.hpp

Реализации метафункции для проверки наличия того или иного метода повторяются. Может стоит определить для них одну общую постановку через #define и дальше генерировать нужные метафункции через этот дефайн? 
За справкой можно обращаться сюда https://docs.microsoft.com/ru-ru/cpp/preprocessor/hash-define-directive-c-cpp?view=msvc-160&viewFallbackFrom=vs-2019 @Shidlowski

**Comment by Shidlowski** [comment]
В dev сделано

**Comment by aaashyrov** [comment]
Не совсем правильно. Можно всю структуру обернуть

**Comment by Shidlowski** [comment]
Структуру в define?
